osx_image: xcode11.4
language: objective-c
xcode_project: RxNimble.xcodeproj
xcode_scheme:
  - RxNimbleRxBlocking
  - RxNimbleRxTest

cache:
  directories:
    - $HOME/Library/Caches/org.carthage.CarthageKit/dependencies
    - Carthage

jobs:
  include:
    - stage: prepare carthage cache
      script:
        - carthage bootstrap --no-use-binaries --cache-builds
    - stage: carthage builds
      script:
        - carthage build --cache-builds --no-skip-current --platform macOS
    - script:
        - carthage build --cache-builds --no-skip-current --platform iOS
    - script:
        - carthage build --cache-builds --no-skip-current --platform tvOS

stages:
  - prepare carthage cache
  - test
  - carthage builds
